name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
      timezone: "Asia/Kolkata"

permissions:
  contents: write
  actions: write

jobs:
  resolver:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - run: pip install beautifulsoup4

      - run: python3 resolver.py

      - run: |
          set -e

          RUNS=$(gh run list --limit 200 --json databaseId -q '.[].databaseId')

          COUNT=0
          for ID in $RUNS; do
            COUNT=$((COUNT+1))
            if [ $COUNT -gt 10 ]; then
              gh run delete "$ID"
            fi
          done
